# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 391, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_devision = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_devision.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_devision.setFont(font)
        self.pushButton_devision.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_devision.setObjectName("pushButton_devision")
        self.gridLayout.addWidget(self.pushButton_devision, 10, 4, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_add.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 7, 4, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 10, 1, 1, 1)
        self.pushButton_multiplication = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_multiplication.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_multiplication.setFont(font)
        self.pushButton_multiplication.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_multiplication.setObjectName("pushButton_multiplication")
        self.gridLayout.addWidget(self.pushButton_multiplication, 9, 4, 1, 1)
        self.pushButton_equals = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_equals.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.gridLayout.addWidget(self.pushButton_equals, 10, 2, 1, 2)
        self.pushButton_substraction = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_substraction.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_substraction.setFont(font)
        self.pushButton_substraction.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_substraction.setObjectName("pushButton_substraction")
        self.gridLayout.addWidget(self.pushButton_substraction, 8, 4, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 7, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 7, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 8, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 8, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 9, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 8, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 9, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 9, 3, 1, 1)
        self.pushButton_delete_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_delete_all.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_delete_all.setFont(font)
        self.pushButton_delete_all.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_delete_all.setObjectName("pushButton_delete_all")
        self.gridLayout.addWidget(self.pushButton_delete_all, 2, 4, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("color: rgb(0, 255, 255);\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0px solid;\n"
"border-radius: 5px;")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 4, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setEnabled(True)
        self.lcdNumber.setMinimumSize(QtCore.QSize(300, 60))
        self.lcdNumber.setMaximumSize(QtCore.QSize(600, 100))
        self.lcdNumber.setSizeIncrement(QtCore.QSize(0, 0))
        self.lcdNumber.setBaseSize(QtCore.QSize(0, 0))
        self.lcdNumber.setStyleSheet("background-color: rgb(126, 126, 126);\n"
"selection-color: rgb(150, 150, 150);\n"
"border:0px solid;\n"
"border-radius: 7px;\n"
"color: rgb(0, 255, 255);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 1, 1, 2, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_devision.setText(_translate("MainWindow", "/"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_multiplication.setText(_translate("MainWindow", "*"))
        self.pushButton_equals.setText(_translate("MainWindow", "="))
        self.pushButton_substraction.setText(_translate("MainWindow", "-"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_delete_all.setText(_translate("MainWindow", "del"))
        self.pushButton_delete.setText(_translate("MainWindow", "<-"))
